#include <catch2/catch_test_macros.hpp>
#include <fwui/pdf_renderer.hpp>
#include <fwui/elements.hpp>
#include <fwui/decorators.hpp>
#include <filesystem>

using namespace fwui;

static bool is_valid_pdf(const std::string& data) {
    return data.size() > 4 && data.substr(0, 5) == "%PDF-";
}

TEST_CASE("PdfRenderer basic output") {
    SECTION("empty div produces valid PDF") {
        auto pdf = PdfRenderer::RenderToString(div({}));
        REQUIRE(is_valid_pdf(pdf));
    }

    SECTION("null element produces empty") {
        auto pdf = PdfRenderer::RenderToString(nullptr);
        REQUIRE(pdf.empty());
    }

    SECTION("paragraph with text") {
        auto pdf = PdfRenderer::RenderToString(p("Hello world"));
        REQUIRE(is_valid_pdf(pdf));
        REQUIRE(pdf.size() > 100);
    }
}

TEST_CASE("PdfRenderer options") {
    PdfRenderer::Options opts;
    opts.page_size = PageSize::Letter();
    opts.title = "Test Document";
    opts.author = "FWUI Tests";
    PdfRenderer renderer(opts);

    auto doc = div({h1("Title"), p("Body")});
    auto pdf = renderer.Render(doc);
    REQUIRE(is_valid_pdf(pdf));
}

TEST_CASE("PdfRenderer RenderToFile") {
    auto doc = div({h1("File Test"), p("Written to disk")});
    auto path = std::filesystem::temp_directory_path() / "fwui_test.pdf";
    PdfRenderer::RenderToFile(doc, path, {});
    REQUIRE(std::filesystem::exists(path));
    REQUIRE(std::filesystem::file_size(path) > 100);
    std::filesystem::remove(path);
}

TEST_CASE("PdfRenderer headings") {
    auto doc = div({
        h1("Heading 1"),
        h2("Heading 2"),
        h3("Heading 3"),
        h4("Heading 4"),
        h5("Heading 5"),
        h6("Heading 6"),
    });
    auto pdf = PdfRenderer::RenderToString(doc);
    REQUIRE(is_valid_pdf(pdf));
    REQUIRE(pdf.size() > 500);
}

TEST_CASE("PdfRenderer inline formatting") {
    SECTION("bold and italic in paragraph") {
        auto doc = p({strong("Bold"), text(" and "), em("italic"), text(" text")});
        auto pdf = PdfRenderer::RenderToString(doc);
        REQUIRE(is_valid_pdf(pdf));
    }

    SECTION("inline code") {
        auto doc = p({text("Use "), code("fwui"), text(" library")});
        auto pdf = PdfRenderer::RenderToString(doc);
        REQUIRE(is_valid_pdf(pdf));
    }
}

TEST_CASE("PdfRenderer block elements") {
    SECTION("code block") {
        auto doc = pre("int main() {\n    return 0;\n}");
        auto pdf = PdfRenderer::RenderToString(doc);
        REQUIRE(is_valid_pdf(pdf));
    }

    SECTION("blockquote") {
        auto doc = blockquote("To be or not to be, that is the question.");
        auto pdf = PdfRenderer::RenderToString(doc);
        REQUIRE(is_valid_pdf(pdf));
    }

    SECTION("horizontal rule") {
        auto doc = div({p("Above"), hr(), p("Below")});
        auto pdf = PdfRenderer::RenderToString(doc);
        REQUIRE(is_valid_pdf(pdf));
    }

    SECTION("line break") {
        auto doc = div({p("Line one"), br(), p("Line two")});
        auto pdf = PdfRenderer::RenderToString(doc);
        REQUIRE(is_valid_pdf(pdf));
    }
}

TEST_CASE("PdfRenderer lists") {
    SECTION("unordered list") {
        auto doc = ul({li("First item"), li("Second item"), li("Third item")});
        auto pdf = PdfRenderer::RenderToString(doc);
        REQUIRE(is_valid_pdf(pdf));
    }

    SECTION("ordered list") {
        auto doc = ol({li("Step one"), li("Step two"), li("Step three")});
        auto pdf = PdfRenderer::RenderToString(doc);
        REQUIRE(is_valid_pdf(pdf));
    }
}

TEST_CASE("PdfRenderer text wrapping") {
    std::string long_text =
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
        "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. "
        "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris "
        "nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in "
        "reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla "
        "pariatur.";
    auto doc = p(long_text);
    auto pdf = PdfRenderer::RenderToString(doc);
    REQUIRE(is_valid_pdf(pdf));
    // Long text should produce more content
    REQUIRE(pdf.size() > 500);
}

TEST_CASE("PdfRenderer complex document") {
    auto doc = div({
        h1("FWUI PDF Report"),
        p("This is a test document generated by FWUI PdfRenderer."),
        h2("Features"),
        ul({
            li("Headings with proper sizing"),
            li("Text wrapping"),
            li("Bold and italic formatting"),
            li("Code blocks"),
            li("Lists"),
        }),
        h2("Code Example"),
        pre("#include <fwui/fwui.hpp>\n\nint main() {\n    auto doc = fwui::h1(\"Hello\");\n    return 0;\n}"),
        h2("Conclusion"),
        p({text("FWUI makes it "), strong("easy"), text(" to generate PDFs from a "),
           em("declarative"), text(" element tree.")}),
    });

    auto pdf = PdfRenderer::RenderToString(doc);
    REQUIRE(is_valid_pdf(pdf));
    REQUIRE(pdf.size() > 1000);
}

TEST_CASE("PdfRenderer page break") {
    // Generate enough content to trigger multiple pages
    Elements children;
    for (int i = 0; i < 60; i++) {
        children.push_back(p("Paragraph " + std::to_string(i + 1) +
            ": Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
            "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."));
    }
    auto doc = div(std::move(children));
    auto pdf = PdfRenderer::RenderToString(doc);
    REQUIRE(is_valid_pdf(pdf));
    // Multi-page doc should be significantly larger
    REQUIRE(pdf.size() > 5000);
}

TEST_CASE("PdfRenderer styled text") {
    auto colored_p = p("Red text");
    colored_p->SetStyle("color", "#FF0000");

    auto doc = div({colored_p});
    auto pdf = PdfRenderer::RenderToString(doc);
    REQUIRE(is_valid_pdf(pdf));
}

TEST_CASE("PdfRenderer tables") {
    SECTION("simple table") {
        auto doc = table({
            tr({th("Name"), th("Value")}),
            tr({td("Alpha"), td("100")}),
            tr({td("Beta"),  td("200")}),
            tr({td("Gamma"), td("300")}),
        });
        auto pdf = PdfRenderer::RenderToString(doc);
        REQUIRE(is_valid_pdf(pdf));
        REQUIRE(pdf.size() > 500);
    }

    SECTION("table with thead/tbody") {
        auto doc = table({
            thead({tr({th("Header 1"), th("Header 2"), th("Header 3")})}),
            tbody({
                tr({td("A1"), td("B1"), td("C1")}),
                tr({td("A2"), td("B2"), td("C2")}),
            }),
        });
        auto pdf = PdfRenderer::RenderToString(doc);
        REQUIRE(is_valid_pdf(pdf));
    }

    SECTION("large table with page breaks") {
        Elements rows;
        rows.push_back(tr({th("ID"), th("Name"), th("Description")}));
        for (int i = 0; i < 50; i++) {
            rows.push_back(tr({
                td(std::to_string(i + 1)),
                td("Item " + std::to_string(i + 1)),
                td("Description for item number " + std::to_string(i + 1)),
            }));
        }
        auto doc = table(std::move(rows));
        auto pdf = PdfRenderer::RenderToString(doc);
        REQUIRE(is_valid_pdf(pdf));
        REQUIRE(pdf.size() > 3000);
    }
}

TEST_CASE("PdfRenderer auto page numbers") {
    PdfRenderer::Options opts;
    opts.auto_page_numbers = true;
    opts.page_number_format = "Page {page} of {total}";
    PdfRenderer renderer(opts);

    Elements children;
    for (int i = 0; i < 40; i++) {
        children.push_back(p("Content paragraph " + std::to_string(i + 1) +
            " with enough text to fill the page. Lorem ipsum dolor sit amet, "
            "consectetur adipiscing elit."));
    }

    auto doc = div(std::move(children));
    auto pdf = renderer.Render(doc);
    REQUIRE(is_valid_pdf(pdf));
}

TEST_CASE("PdfRenderer header and footer callbacks") {
    PdfRenderer::Options opts;
    opts.title = "Report with Headers";
    opts.header = [](int page_num, int /*total*/) -> Element {
        return text("Document Header - Page " + std::to_string(page_num));
    };
    opts.footer = [](int /*page_num*/, int total) -> Element {
        return text("Total pages: " + std::to_string(total));
    };
    PdfRenderer renderer(opts);

    auto doc = div({
        h1("Report Title"),
        p("Some content in the report body."),
        p("More content here."),
    });
    auto pdf = renderer.Render(doc);
    REQUIRE(is_valid_pdf(pdf));
}

TEST_CASE("PdfRenderer full document with all features") {
    PdfRenderer::Options opts;
    opts.title = "FWUI Full Feature Test";
    opts.author = "Test Suite";
    opts.auto_page_numbers = true;
    PdfRenderer renderer(opts);

    auto doc = div({
        h1("Full Feature PDF Test"),
        p({text("This tests "), strong("bold"), text(", "), em("italic"),
           text(", and "), code("monospace"), text(" inline formatting.")}),
        h2("Table"),
        table({
            thead({tr({th("Feature"), th("Status")})}),
            tbody({
                tr({td("Headings"),  td("OK")}),
                tr({td("Paragraphs"), td("OK")}),
                tr({td("Tables"),    td("OK")}),
                tr({td("Lists"),     td("OK")}),
            }),
        }),
        h2("Lists"),
        ul({li("Unordered item 1"), li("Unordered item 2")}),
        ol({li("Ordered item 1"), li("Ordered item 2")}),
        h2("Code"),
        pre("def hello():\n    print('Hello, World!')"),
        blockquote("This is a blockquote for emphasis."),
        hr(),
        p("End of document."),
    });

    auto pdf = renderer.Render(doc);
    REQUIRE(is_valid_pdf(pdf));
    REQUIRE(pdf.size() > 2000);
}
